Fix next.jdbc.date-time for java.sql.Date
An insert fails with
> UnsupportedOperationException: null at java.sql/java.sql.Date.toInstant(Date.java:316)

if you required `next.jdbc.date-time` and the value you are inserting is `java.sql.Date` because it is a subclass of `java.util.Date` and thus gets handled by https://github.com/seancorfield/next-jdbc/blob/master/src/next/jdbc/date_time.clj#L45 - but it doesn't support `toInstant` contrary to its superclass.

The solution is to use `.setDate` with the value as-is instead of `.setTimestamp`.